# Unique test queries across 50 distinct real-world domain scenarios
# Explicitly raw user questions without reference/stored answers.

DIVERSE_TEST_QUESTIONS = [
    "How many active books are currently available in the system catalog?",
    "Find the top 5 highest customer orders by total invoice value.",
    "List all doctors scheduled for appointments next Monday.",
    "Count the number of IoT sensors reporting high temperature alerts.",
    "Show total students enrolled in Advanced Machine Learning this semester.",
    "Retrieve all hotel rooms booked for the upcoming weekend conference.",
    "List all open high-priority bug tickets assigned to frontend engineering.",
    "Calculate the total payment transaction volume processed in the last 24 hours.",
    "Find all files backed up to cloud storage larger than 100 megabytes.",
    "List employees in the Marketing department hired within the past year.",
    "Find the top 3 best-selling dishes on the restaurant dinner menu.",
    "Show available rental cars located at the airport branch with GPS navigation.",
    "Retrieve passenger names for flight BA2490 scheduled for departure tomorrow.",
    "Count total inventory items currently below minimum safety stock levels.",
    "Find all unresolved customer support tickets with SLA expiration in 2 hours.",
    "List the latest crypto wallet transactions exceeding 1.5 Ethereum.",
    "Retrieve real estate listings with at least 3 bedrooms priced under 500k.",
    "Calculate average weekly running distance logged by premium app members.",
    "Show the most streamed podcast episodes in the Technology category this week.",
    "List all smart home devices currently connected to the living room hub.",
    "Find total pending insurance claims submitted for automotive damage.",
    "Show weekly meal plan recipes containing less than 600 calories per serving.",
    "Retrieve all unpaid freelancer invoices overdue by more than 30 days.",
    "List available EV charging stations with fast-charging DC connectors.",
    "Show VIP event tickets sold for the summer music festival.",
    "Generate top upbeat pop songs added to workout playlists this month.",
    "Retrieve active legal contracts due for annual renewal within 60 days.",
    "List international freight shipments currently in customs transit status.",
    "Calculate total charity donations received during the holiday campaign.",
    "Show the top 10 player scores on the global multiplayer leaderboard.",
    "List industrial equipment units overdue for quarterly preventative maintenance.",
    "Retrieve all tasks in the 'In Review' column on the sprint Kanban board.",
    "Find all digital marketing assets tagged with the 'Q4 Campaign' label.",
    "Calculate average network packet latency recorded over the past hour.",
    "List job applicants who successfully passed the technical coding interview.",
    "Find server hosts with critical security vulnerabilities detected in scan.",
    "Retrieve patient medical records updated by the cardiology clinic today.",
    "Count total students who completed the online certification exam on time.",
    "Show engagement metrics for social media posts published in the last 7 days.",
    "Find microservice routes experiencing HTTP 500 error rates above 1 percent.",
    "List reserved parking spots in the downtown garage between 9 AM and 5 PM.",
    "Retrieve breaking news headlines published in the Technology section.",
    "Show drone flight paths scheduled over the northern agricultural sector.",
    "Find employee expense reimbursement requests awaiting managerial signoff.",
    "List digital documents pending electronic signature from external clients.",
    "Calculate optimal reorder quantities for high-demand warehouse SKU parts.",
    "Retrieve final grade distribution metrics for the introductory physics course.",
    "Count API client requests blocked by the rate limiter during traffic spikes.",
    "Analyze maintainability index and cyclomatic complexity across codebase files.",
    "Find top relevant knowledge base articles for troubleshooting database timeout."
]
